Repository Waidhoferj/cpe-messenger, pull requests merged in 2019-11, with the labels that each got.

#15 Fixes issue #10: Needed to destructure state from context (use {})
  src/store.js
Labels: bug

#19 Added missing "s" to the router-link for Announcements
  src/App.vue
Labels: bug

#20 Fixes issue #17: Announcer clears schedule fields on send
  src/components/Announcer.vue
Labels: bug

#23 Fixes issue #18: response-bar now sizes parent grid
  src/views/Conversations.vue
Labels: bug

#24 Fixes issue #12: member counter added to Groups screen
  src/views/Groups.vue
Labels: enhancement

#29 Local group add
  src/components/GroupPopup.vue
  src/store.js
  src/views/Groups.vue
Labels: bug

#32 Fixes issues #31 and #28
  src/App.vue
  src/assets/file-icon.svg
  src/components/GroupPopup.vue
  src/store.js
  src/views/Conversations.vue
  src/views/Groups.vue
Labels: bug, enhancement

#34 Fixes issue #33 and additional problem with groupNames
  src/components/Announcer.vue
  src/components/GroupPopup.vue
Labels: bug

#39 Group form no longer sends empty form request on button click
  src/components/GroupPopup.vue
Labels: bug

#44 Fixes issue #43: Announcements queue created
  src/App.vue
  src/components/Announcer.vue
  src/components/EventCalendar.vue
  src/components/Notifications.vue
  src/components/QueuedMessage.vue
  src/modules/listeners.js
  src/store.js
  src/views/Announcements.vue
Labels: enhancement
